# Generated by Django 2.2.5 on 2019-09-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalView', '0002_keyplayers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='keyPlayers',
            new_name='keyPlayer',
        ),
    ]
