# Generated by Django 2.2.5 on 2019-09-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalView', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
