# Generated by Django 2.2.5 on 2019-09-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalView', '0009_auto_20190928_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_detail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
