# Generated by Django 2.2.5 on 2019-09-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalView', '0010_task_task_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_detail',
        ),
        migrations.AddField(
            model_name='event',
            name='task_detail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
