# Generated by Django 2.2.5 on 2019-09-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalView', '0011_auto_20190928_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='task_detail',
            field=models.CharField(default='', max_length=600),
        ),
    ]
